proxy:
    title:
    landing-page: /
    heartbeat-rate: 15000
    heartbeat-timeout: 3600000 # 1 Hour the time in milliseconds that the server must receive no heartbeat in order to terminate the proxy.
    port: 9191
    template-path: ./templates/1col
    container-wait-time: 20000
    container-log-path: ./container-logs
    support:
      mail-to-address: luna.remnrem@gmail.com
  
    authentication: none
    usage-stats-url: micrometer
    usage-stats-micrometer-prefix: shinyproxy

    docker:
      cert-path: /home/none
      url: http://localhost:2375
      port-range-start: 20000
      port-range-max: 20016

    specs:
    - id: moonlight
      display-name: Moonlight
      container-cmd: ["R", "-e", "shiny::runApp('/root/moon')"]
      container-image: moonlight-moonbeam-may02-2023
      max-instances: 1

management:
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: shinyproxy.log
