proxy:
    title:
    landing-page: /
    heartbeat-rate: 10000
    heartbeat-timeout: 1800000 # 30 min the time in milliseconds that the server must receive no heartbeat in order to terminate the proxy.
    port: 9191
    template-path: ./templates/1col
    container-wait-time: 20000
    container-log-path: ./container-logs # Please make sure to set permission ( chown shinyproxy:shinyproxy container-logs/ )
    support:
      mail-to-address: luna.remnrem@gmail.com
  
    authentication: none
    usage-stats-url: micrometer
    usage-stats-micrometer-prefix: shinyproxy

    docker:
      url: http://localhost:2375
      port-range-start: 20000
      port-range-max: 20016

    specs:
    - id: moonlight
      display-name: Moonlight
      description: Moonlight
      container-cmd: ["R", "-e", "shiny::runApp('/root/moon')"]
      container-image: moonlight-moonbeam-nov27-2024
      max-instances: 1
    - id: hypnoscope
      display-name: Hypnoscope
      description: Hypnoscope
      container-cmd: ["R", "-e", "shiny::runApp('/root/hypnoscope')"]
      container-image: hypnoscope-apr25-2024
      max-instances: 1

management:
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  file:
    name: shinyproxy.log
